name: ae-poc-identity
services:
  identity-api:
    image: identity-api:v1.0.4
    container_name: ae-poc-identity-webapi
    build:
      context: .
      dockerfile: ae-poc-identity-webapi/Dockerfile
    ports:
      - "5023:8080"
      - "9008:9008"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - Health__Port=9008
